import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import { useRouter } from 'next/router';
const headers = [
    {
      title: "Header 1",
      url: "",
    },
    {
      title: "Header 2",
      url: "chatBox",
    },
    {
      title: "Header 3",
      url: "speeh",
    },
  ];

const HeaderList = ({ headers, activateIndex, onHeaderClick }) => {
    return (
            <div className='header__menu'>
                {headers.map((header, index)=>(
                    <Header 
                        key = {index}
                        title={header.title}
                        url={header.url}
                        isActivated= {index === activateIndex}
                        onClick = {()=>onHeaderClick(index)}
                    />
                ))}
            </div>
    )
}

const Header = ({title, url, isActivated, onClick}) => {
    const router = useRouter()
    const handleClick = (event) => {
        event.preventDefault()
        onClick()
        router.push(`/${url}`)
      }
    return (
        <div className={`header__menu-item  ${isActivated ? 'active' : ''}`} >
        <a href = {`/${url}`} onClick={handleClick}>{title}</a>
        </div>
    )    
}

export default function HeaderView () {
    const [activateIndex, setActivateIndex] = useState(0);
    const headerHeaderClick = (index) => {
        setActivateIndex(index)
    }
    return (
        <>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="header">
        <div className="header__logo">
        <Link href = {`/`}>Tu Tu</Link></div>
        <HeaderList 
            headers={headers} 
            activateIndex={activateIndex}
            onHeaderClick={headerHeaderClick}
            />
        </div>
        </>
    )
}